### ISSUE TITLE
How to run the source code in src?

### ISSUE THREAD

**Issue by michaelwangyuan** [iamalexkorotin/WassersteinIterativeNetworks#2]
Thank you for your fancy work. 
What should I do if I want to run the source code in src folder? E.g.  to find the optimal map between two real world distributions.

**Comment by iamalexkorotin** [comment]
This is repository for computing the barycenters, not Optimal Transport maps.

If you want to compute the OT map between real data distributions, pls check the other repo
https://github.com/iamalexkorotin/NeuralOptimalTransport/
and the following notebook (all the training code is inside, src just contains auxiliary stuff, e.g., dataloaders):
https://github.com/iamalexkorotin/NeuralOptimalTransport/blob/main/notebooks/NOT_training_strong.ipynb
To apply it to some other (image) data, you just need to replace the dataloaders code with the ones for your data.

Hope this helps!
Alex
